Repository medizininformatik-initiative/fhir-ontology-generator, pull requests merged in 2025-05, with the labels that each got.

#251 Adding module name + translation to profile details
  data_selection_extraction/core/generators/profile_detail.py
  data_selection_extraction/model/detail.py
  data_selection_extraction/scripts/generate_dse_files.py
  projects/fdpg-ontology/input/dse/module_config.json
Labels: dse

#265 Implement compaction of DSE profile tree
  data_selection_extraction/core/generators/profile_detail.py
  data_selection_extraction/core/generators/profile_tree.py
  data_selection_extraction/model/profile_tree.py
  data_selection_extraction/util/fhir/__init__.py
  data_selection_extraction/util/fhir/profile.py
Labels: dse

#261 225 update test blood pressure with composite to new structure new file structure
  .github/workflows/run-integration-tests.yml
  cohort_selection_ontology/core/generators/cql.py
  test/integration/backend/Composite_test.py
  test/integration/projects_for_testing/projects/composite/input/modules/ICU/QueryingMetaData/SD_MII_ICU_Arterieller_BlutdruckQueryingMetaData.json
  test/integration/projects_for_testing/projects/composite/input/modules/ICU/differential/package/sd-mii-icu-muv-arterieller-blutdruck-snapshot.json
  test/integration/projects_for_testing/projects/composite/input/modules/ICU/expected/cql_mapping.json
  test/integration/projects_for_testing/projects/composite/input/modules/ICU/expected/ui_profile.json
Labels: tests

#269 Update docs
  README.md
  cohort_selection_ontology/README.md
  docs/DSE-README.md
  docs/Elastic-README.md
  docs/Merger-README.md
  docs/Parcel-README.md
  ontology_merging/README.md
Labels: documentation, enhancement, refactor

#276 Fix missing references to UI profiles for contextualized term code entries
  .env
  .github/workflows/ci.yml
  .github/workflows/generate-ontology.yml
  cohort_selection_ontology/util/database.py
  common/util/http/terminology/client.py
  common/util/project/__init__.py
  common/util/sql/merging.py
  projects/fdpg-ontology/generate_ontology.py
  requirements.txt
Labels: bug

#278 270 missing records in sql script files
  .env
  .github/workflows/ci.yml
  .github/workflows/generate-ontology.yml
  cohort_selection_ontology/util/database.py
  common/util/http/terminology/client.py
  common/util/project/__init__.py
  common/util/sql/merging.py
  projects/fdpg-ontology/generate_ontology.py
  requirements.txt
  test/integration/backend/conftest.py
  test/integration/conftest.py
  test/integration/integrity/__init__.py
  test/integration/integrity/database/__init__.py
  test/integration/integrity/database/conftest.py
  test/integration/integrity/database/docker-compose.yml
  test/integration/integrity/database/sql_import_test.py
Labels: bug, tests

#279 274 module icu named incorrectly for dse
  projects/fdpg-ontology/input/dse/module_config.json
Labels: dse

#283 Release v3.7.0
  CHANGELOG.md
Labels: release
